version: "3.9"

services:
  mongo:
    image: mongo
    restart: always
    volumes:
      - ./mongodb:/data/db
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
  api:
    build: ./api
    restart: always
    ports:
      - 4000:4000
    environment:
      API_MONGODB_CONNECTION_URI: mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@mongo
  webapp:
    build: ./webapp
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    environment:
      WEBAPP_GOOGLE_MAPS_KEY: ${GOOGLE_MAPS_KEY}
